In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch

### data loading

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [37]:
df.shape

(569, 33)

In [38]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [39]:
df.shape

(569, 31)

### train test split

In [40]:
# X = Features (independent variables), y = Target (what you want to predict)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],
    test_size=0.2,       # 20% allocated to the test set
    random_state=42,     # Ensures the split is reproducible
    stratify=df.iloc[:,0]         # Keeps the balance of target classes consistent
)

### scaling

In [41]:
scaler = StandardScaler()

# 3. Fit on the training data ONLY and transform it
X_train = scaler.fit_transform(X_train)

# 4. Transform the test data using the training parameters (Do NOT refit!)
X_test = scaler.transform(X_test)

In [42]:
X_train

array([[ 0.51855873,  0.89182579,  0.4246317 , ..., -0.23574392,
         0.05456632,  0.02183673],
       [-0.51636409, -1.63971029, -0.54134872, ..., -0.32320788,
        -0.13757624, -0.90440164],
       [-0.36811839,  0.45551496, -0.38824993, ..., -0.89082504,
        -0.675893  , -0.14401559],
       ...,
       [-0.32616206,  1.33280304, -0.38905998, ..., -0.84289958,
        -0.96490082, -1.16888375],
       [ 0.00948859,  0.25952507,  0.00786279, ...,  0.27571059,
        -0.60284707, -0.30545988],
       [ 0.80945595,  0.36918608,  0.79320285, ...,  1.00657384,
        -0.46151907, -0.44817001]])

In [43]:
X_train.shape

(455, 30)

### Label Encoding

In [44]:
y_train

10     M
170    B
407    B
430    M
27     M
      ..
37     B
415    B
458    B
476    B
335    M
Name: diagnosis, Length: 455, dtype: object

In [45]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
print(y_train)

[1 0 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 0
 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 1 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 1 0
 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 1 1
 0 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1
 1 1 0 0 1 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 1 0
 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 1 0
 0 0 0 1 1 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0
 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1
 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1
 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1
 1 0 0 0 0 0 0 0 0 0 1]

### Numpy arrays to PyTorch tensors

In [46]:
type(X_train)

numpy.ndarray

In [47]:
y_train.shape

(455,)

In [48]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [54]:
y_train_tensor.shape

torch.Size([455])

### Define the neural network

In [73]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_calculation(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [74]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [75]:
model = MySimpleNN(X_train)

In [76]:
model.weights

tensor([[0.6942],
        [0.8708],
        [0.8005],
        [0.6824],
        [0.0894],
        [0.4930],
        [0.3680],
        [0.8128],
        [0.8541],
        [0.5292],
        [0.6019],
        [0.0515],
        [0.3442],
        [0.2144],
        [0.8427],
        [0.9757],
        [0.2443],
        [0.2149],
        [0.9357],
        [0.9068],
        [0.0618],
        [0.1807],
        [0.2383],
        [0.6057],
        [0.6833],
        [0.5728],
        [0.1950],
        [0.8634],
        [0.7377],
        [0.4268]], dtype=torch.float64, requires_grad=True)

In [77]:
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train_tensor)
  # calculate loss
  loss = model.loss_calculation(y_pred, y_train_tensor)

  # backpropogation
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.763321641673857
Epoch: 2, Loss: 3.6408326696696633
Epoch: 3, Loss: 3.514270004925163
Epoch: 4, Loss: 3.3856958879892023
Epoch: 5, Loss: 3.255515466161576
Epoch: 6, Loss: 3.1230291445283984
Epoch: 7, Loss: 2.986092555378127
Epoch: 8, Loss: 2.8455552917005633
Epoch: 9, Loss: 2.70526953333767
Epoch: 10, Loss: 2.555633073026723
Epoch: 11, Loss: 2.4039537484099154
Epoch: 12, Loss: 2.2516879561541074
Epoch: 13, Loss: 2.09594468794202
Epoch: 14, Loss: 1.9380895035172003
Epoch: 15, Loss: 1.7891986846370078
Epoch: 16, Loss: 1.649742985100885
Epoch: 17, Loss: 1.519585503685934
Epoch: 18, Loss: 1.400235470153906
Epoch: 19, Loss: 1.288959327870713
Epoch: 20, Loss: 1.1926849610793693
Epoch: 21, Loss: 1.1114523968727563
Epoch: 22, Loss: 1.044640857413698
Epoch: 23, Loss: 0.9909861277161763
Epoch: 24, Loss: 0.9486629209192056
Epoch: 25, Loss: 0.9155144650324072

In [78]:
model.bias

tensor([-0.1089], dtype=torch.float64, requires_grad=True)

### Evaluation

In [80]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.85).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6061865091323853